name: My First Workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v6
        - name: List and read file
          run: |
            echo "My first Github Actions Job"
            ls -ltra
            cat README.md
        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover,i am a DRAGON ....RAWR" >> dragon.txt
        #- name: List files
        #  run: ls
        #- name: read file
        #  run: cat README.md