name: Generate ASCII Artwork
on: push
jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Install cowsay programm
      run: sudo apt-get install cowsay -y
    - name: Execute cowsay cmd
      run: cowsay -f dragon "Run for cover,I am a DRAGON ... RAWR" >> dragon.txt 
    - name: sleep for 30 seconds
      run: sleep 30
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Dragon-Text-File
        path: dragon.txt
  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v5
      with:
        name: Dragon-Text-File
    - name: sleep for 10 seconds
      run: sleep 10
    - name: Test file exists
      run: grep -i "dragon" dragon.txt
  deploy_job_3:
    needs: test_job_2
    runs-on: ubuntu-latest
    steps:
    - name: Download Arftfact
      uses: actions/download-artifact@v5
      with:
        name: Dragon-Text-File
    - name: Read file
      run: cat dragon.txt
    - name: Deploy
      run: echo Deploying ....

 